from sqlalchemy import Boolean, Float, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column

from app.database import Base


class CustomerIntelligence(Base):
    __tablename__ = "customer_intelligence"

    customer_id: Mapped[str] = mapped_column(String, primary_key=True, index=True)
    age: Mapped[int] = mapped_column(Integer)
    gender: Mapped[str] = mapped_column(String)
    region: Mapped[str] = mapped_column(String)
    acquisition_channel: Mapped[str] = mapped_column(String)
    subscription_type: Mapped[str] = mapped_column(String)
    contract_type: Mapped[str] = mapped_column(String)
    tenure_months: Mapped[int] = mapped_column(Integer)
    monthly_revenue: Mapped[float] = mapped_column(Float)
    total_revenue: Mapped[float] = mapped_column(Float)
    number_of_products_used: Mapped[int] = mapped_column(Integer)
    number_of_logins_last_30_days: Mapped[int] = mapped_column(Integer)
    average_session_duration: Mapped[float] = mapped_column(Float)
    feature_usage_score: Mapped[float] = mapped_column(Float)
    support_tickets_last_90_days: Mapped[int] = mapped_column(Integer)
    unresolved_tickets: Mapped[int] = mapped_column(Integer)
    late_payments: Mapped[int] = mapped_column(Integer)
    discount_used: Mapped[bool] = mapped_column(Boolean)
    payment_method: Mapped[str] = mapped_column(String)
    satisfaction_score: Mapped[float] = mapped_column(Float)
    nps_score: Mapped[int] = mapped_column(Integer)
    last_interaction_days_ago: Mapped[int] = mapped_column(Integer)
    marketing_email_open_rate: Mapped[float] = mapped_column(Float)
    campaign_click_rate: Mapped[float] = mapped_column(Float)
    customer_success_calls: Mapped[int] = mapped_column(Integer)
    renewal_due_in_days: Mapped[int] = mapped_column(Integer)
    churn: Mapped[int] = mapped_column(Integer)
    engagement_score: Mapped[float] = mapped_column(Float)
    support_pressure_score: Mapped[float] = mapped_column(Float)
    payment_risk_score: Mapped[float] = mapped_column(Float)
    revenue_per_product: Mapped[float] = mapped_column(Float)
    customer_age_group: Mapped[str] = mapped_column(String)
    tenure_group: Mapped[str] = mapped_column(String)
    renewal_risk_flag: Mapped[bool] = mapped_column(Boolean)
    high_value_customer_flag: Mapped[bool] = mapped_column(Boolean)
    churn_probability: Mapped[float] = mapped_column(Float, index=True)
    estimated_clv: Mapped[float] = mapped_column(Float, index=True)
    revenue_at_risk: Mapped[float] = mapped_column(Float)
    potential_revenue_saved: Mapped[float] = mapped_column(Float)
    cluster_id: Mapped[int] = mapped_column(Integer)
    segment: Mapped[str] = mapped_column(String, index=True)
    segment_strategy: Mapped[str] = mapped_column(Text)
    recommended_action: Mapped[str] = mapped_column(String)
    recommendation_explanation: Mapped[str] = mapped_column(Text)
    priority_level: Mapped[str] = mapped_column(String, index=True)
    estimated_action_cost: Mapped[float] = mapped_column(Float)
    expected_success_probability: Mapped[float] = mapped_column(Float)
    expected_revenue_impact: Mapped[float] = mapped_column(Float)
    expected_revenue_saved: Mapped[float] = mapped_column(Float)
    top_churn_reasons: Mapped[str] = mapped_column(Text)
